### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by alibustami** [elliottzheng/batch-face#6]
When running command 
`pip install git+https://github.com/elliottzheng/batch-face.git@master`
on Ubuntu 20.04.4 LTS x86_64 
I get this error

`ERROR: Command errored out with exit status 1:
     command: /home/alibustami/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fk2_4kiw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fk2_4kiw/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dylf4bz4
         cwd: /tmp/pip-req-build-fk2_4kiw/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-fk2_4kiw/setup.py", line 5, in <module>
        import batch_face
      File "/tmp/pip-req-build-fk2_4kiw/batch_face/__init__.py", line 2, in <module>
        from .utils import drawLandmark_multiple, detection_adapter, bbox_from_pts, Aligner
      File "/tmp/pip-req-build-fk2_4kiw/batch_face/utils.py", line 1, in <module>
        import cv2
    ModuleNotFoundError: No module named 'cv2'
    ----------------------------------------
WARNING: Discarding git+https://github.com/elliottzheng/batch-face.git@master. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by elliottzheng** [comment]
You need to first install the following requirements

https://github.com/elliottzheng/batch-face#requirements

you get error because you don't have opencv-python installed
