### ISSUE TITLE
Support for image downscaling

### ISSUE THREAD

**Issue by aimeiai** [elliottzheng/batch-face#8]
Hi,

This project is great, thank you for the work - testing with GPU acceleration it beats most other face detectors out there (insightface, centerface, different implementations of retinaface, etc.).

Is there any chance to add support to downscale the image before detection (in GPU preferably)?

Like in this project - https://github.com/ORB-HD/deface/blob/1e6a87fbf7dd92c16d36418ed019ea8781ca1d72/deface/centerface.py#L101

Thank you!

**Comment by elliottzheng** [comment]
now you can specify max_size or resize factor in detector call, check [here](https://github.com/elliottzheng/batch-face?tab=readme-ov-file#batch-input-for-faster-detection)
